# Site settings
baseURL = "https://www.veevo.org/"
languageCode = "en-us"
title = "Veevo"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Veevo.org"
  description = "Know thyself"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Veevo"
    subtitle = "Know thyself"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Spiritism"
      url = "en/spiritism"

    [[params.navigation.links]]
      name = "Q&A"
      url = "en/questions"

    [[params.navigation.links]]
      name = "Universal Laws"
      url = "en/laws"

    [[params.navigation.links]]
      name = "Jesus"
      url = "en/about/jesus"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Resources"
      url = "/en/resources"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Get Started"
      url = "en/get-started"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, welcome to Veevo!"
    subtitle = "A PROJECT DEDICATED TO ENLIGHTEN HUMANITY TRHOUGH THE LIGHTS OF THE IMMORTAL SPIRIT"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Get Started"
      subtitle = "Don't know where to start? Start here"
      image = "pic01.jpg"
      url = "/en/get-started"

    [[params.tiles.showcase]]
      title = "Spiritism"
      subtitle = "Know what is Spiritism, the \"Comforter\" announced in the Bible"
      image = "pic02.jpg"
      url = "en/spiritism"

    [[params.tiles.showcase]]
      title = "Questions and Answers"
      subtitle = "Ever wanted to know the real truth behind depression, suicide, abortion and other polemic topics? Check our database to know more."
      image = "pic03.jpg"
      url = "en/questions"

    [[params.tiles.showcase]]
      title = "Universal Laws"
      subtitle = "Learn about the Universal Laws, how they govern the Universe and how they affect us"
      image = "pic04.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Meet Jesus"
      subtitle = "We will help you learn more about Jesus, the Son of God"
      image = "pic05.jpg"
      url = "en/about/jesus"

    [[params.tiles.showcase]]
      title = "Resources"
      subtitle = "Looking for Movies, Books, Bios and Authors? Find them here"
      image = "pic06.jpg"
      url = "en/resources"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Our mission"
    subtitle = " Veevo hopes to enlighten humanity about polemic issues such as: death, depression, aborption, suicide, family conflicts, marriage, society issues, and more. Why should you care? Because our material is based on the immortal and immutable teachings of Spiritism, a doctrine composed of Science, Religion and Philosofy, more commonly described as the Helper as announced by Jesus in John 14:26."
	buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "xnqgerev"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "contact@veevo.org"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Veevo.org"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/veevo"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/veevo"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/veevo"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/veevo"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/veevo"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      url= "en/about"
      alt = "About"

    [[params.footer.quicklinks]]
      url= "en/help"
      alt = "Help"

    [[params.footer.quicklinks]]
      url= "en/contact"
      alt = "Contact"

    [[params.footer.quicklinks]]
      #url= "en/contact"
      #alt = "Contact"
	  text = "All material on this site is free and can be freely reproduced and distributed"

